export const {
  SERVER_API_BASE_URL,
  SERVER_API_VERSION_V1,
  NEXT_PUBLIC_API_ROUTE_BASE_URL,
} = process.env;
export const SERVER_API_V1_BASE_URL = `${SERVER_API_BASE_URL}${SERVER_API_VERSION_V1}`;

const API_RESOURCES = {
  MEMBERS: '/members',
};

export const AUTH_ENDPOINTS = {
  EMAIL_VERIFY: `${API_RESOURCES.MEMBERS}/email/verify`,
  EMAIL_CONFIRM: `${API_RESOURCES.MEMBERS}/email/confirm`,
  SIGNUP_EMAIL: `${API_RESOURCES.MEMBERS}/signup/email`,
  RESET_PW: `${API_RESOURCES.MEMBERS}/password/reset`,
  SIGNIN_EMAIL: `${API_RESOURCES.MEMBERS}/login/email`,
};

export const PRODUCT_PATHS = {
  LIST: '/products',
  LATEST: '/products/latest',
  DETAIL: '/products/:productId',
  RECOMMEND: '/products/recommend',
};

export const PRODUCTS_ENDPOINTS = {
  LIST: `${SERVER_API_BASE_URL}${SERVER_API_VERSION_V1}${PRODUCT_PATHS.LIST}`,
  LATEST: `${SERVER_API_BASE_URL}${SERVER_API_VERSION_V1}${PRODUCT_PATHS.LATEST}`,
  DETAIL: `${SERVER_API_BASE_URL}${SERVER_API_VERSION_V1}${PRODUCT_PATHS.DETAIL}`,
  RECOMMEND: `${SERVER_API_BASE_URL}${SERVER_API_VERSION_V1}${PRODUCT_PATHS.RECOMMEND}`,
};
