export const SERVER_API_BASE_URL = process.env.SERVER_API_BASE_URL;
export const SERVER_API_VERSION_V1 = process.env.SERVER_API_VERSION_V1;
export const API_ROUTE_BASE_URL = process.env.API_ROUTE_BASE_URL;

export const USERS_ENDPOINTS = {
  LIST: `${SERVER_API_BASE_URL}${SERVER_API_VERSION_V1}/users`,
};

export const PRODUCT_PATHS = {
  LIST: '/products',
  LATEST: '/products/latest',
  DETAIL: '/products/:productId',
  RECOMMEND: '/products/recommend',
};

export const PRODUCTS_ENDPOINTS = {
  LIST: `${SERVER_API_BASE_URL}${SERVER_API_VERSION_V1}${PRODUCT_PATHS.LIST}`,
  LATEST: `${SERVER_API_BASE_URL}${SERVER_API_VERSION_V1}${PRODUCT_PATHS.LATEST}`,
  DETAIL: `${SERVER_API_BASE_URL}${SERVER_API_VERSION_V1}${PRODUCT_PATHS.DETAIL}`,
  RECOMMEND: `${SERVER_API_BASE_URL}${SERVER_API_VERSION_V1}${PRODUCT_PATHS.RECOMMEND}`,
};
