name: ✨ design
description: UX/UI 관련 디자인을 추가하거나 수정합니다
title: '[✨ design] '
labels: ['✨ design']
body:
  - type: textarea
    id: design-description
    attributes:
      label: 📄 설명
      description: |
       새로운 UX/UI 대한 설명을 자세히 작성해 주세요.
       - 
      placeholder:
    validations:
      required: true
  - type: textarea
    id: design-simulation
    attributes:
      label: ✨ Design Tasks
      description: |
       Design Tasks를 최대한 세분화해서 작성해 주세요.
       - [ ] 체크박스
      placeholder:
    validations:
      required: true
  - type: textarea
    id: design-more
    attributes:
      label: 📝 메모
      description: 더 하고 싶은 말이 있다면 작성해 주세요.
    validations:
      required: false
