name: ✨ feat
description: 새로운 기능을 구현하거나 기존 기능을 확장합니다.
title: '[✨ feat] '
labels: ['✨ feat']
body:
  - type: textarea
    id: feat-description
    attributes:
      label: 📄 설명
      description: |
       새로운 기능에 대한 설명을 자세히 작성해 주세요.
       - 
      placeholder:
    validations:
      required: true
  - type: textarea
    id: feat-simulation
    attributes:
      label: ✨ Feat Tasks
      description: |
       Feat Tasks를 최대한 세분화해서 작성해 주세요.
       - [ ] 체크박스
      placeholder:
    validations:
      required: true
  - type: textarea
    id: feat-more
    attributes:
      label: 📝 메모
      description: 더 하고 싶은 말이 있다면 작성해 주세요.
    validations:
      required: false
